
title: "Todd's Blog"
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
  Thought.Knowledege.Life.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

permalink: /:year/:month/:title

# Social 社交
social:
  - bilibili:
    icon: bilibili
    url: https://space.bilibili.com/14158798
  - github:
    icon: github
    url: https://github.com/toddzzf

# Pagination 分页
paginate: 12
paginate_path: "/page:num/" # 分页的url

# Excerpt 摘要
excerpt_separator: <!--more--> # 摘要的分隔符
excerpt_max_num: 64 # 摘要的最大长度

# Plugins 插件
plugins:
  - jekyll-feed
  - jekyll-paginate

exclude:
  - .gitattributes
  - .gitignore
  - .sass-cache/
  - .jekyll-cache/
  - _site/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - node_modules/
  - src/
  - README.md
  - tailwind.config.js
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

collections:
  my_ppt:
    output: true
    permalink: /:year-:month-:day/:title